name: linked_list_composition
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  clean_test:
    git:
      url: git@github.com:mohammadtaherri/clean_test.git
      ref: f65bca0f2905709a9efb90fed7452e76f6ad53a1