name: queue
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  linked_list:
    path: ../linked_list
  stack:
    path: ../stack

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dartunit: ^1.0.0+2
